# Generated by Django 4.1.5 on 2023-02-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilmsOnMainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_id', models.IntegerField(verbose_name='ID Фильма')),
                ('category', models.CharField(max_length=30, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Фильм на главной странице',
                'verbose_name_plural': 'Фильмы на главной сранице',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email пользователя')),
                ('username', models.CharField(max_length=50, verbose_name='Юзернейм пользователя')),
                ('password', models.CharField(max_length=300, verbose_name='Пароль пользователя (sha256)')),
                ('date_register', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
