# Generated by Django 4.1.5 on 2023-01-31 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmsOnMainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_id', models.IntegerField(verbose_name='ID Фильма')),
                ('category', models.CharField(max_length=30, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Фильм на главной странице',
                'verbose_name_plural': 'Фильмы на главной сранице',
            },
        ),
    ]
