# Generated by Django 4.1.5 on 2023-02-12 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_filmsonmainpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
