# Generated by Django 4.1.5 on 2023-02-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_user_first_name_remove_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='1111111111aleksey46@gmail.com', max_length=254, verbose_name='Email пользователя'),
            preserve_default=False,
        ),
    ]
